name: everything
description: "HTML web dosyalarını sohbet yoluyla oluşturan uygulama"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Durum yönetimi
  provider: ^6.1.0
  # Yönlendirme
  go_router: ^13.2.0
  # Yerel depolama
  shared_preferences: ^2.2.2
  # HTTP istekleri
  dio: ^5.4.0
  # Yardımcı araçlar
  flutter_hooks: ^0.20.3
  # UI bileşenleri
  google_fonts: ^5.1.0
  # Kimlik doğrulama
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  # AI ve HTTP
  web_socket_channel: ^2.4.0
  html: ^0.15.4
  # Web görüntüleme
  webview_flutter: ^4.4.2
  timeago: ^3.6.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo.png
    - assets/images/login_background.jpg
